WHENEVER SQLERROR CONTINUE;

SHOW CON_NAME;

SHOW PDBS;

ALTER SESSION SET CONTAINER=localdb;

SHOW CON_NAME;

--CREATE USER myuser IDENTIFIED BY "MYPASSWORD";

--GRANT CREATE SESSION TO myuser;
--GRANT RESOURCE TO myuser;
--GRANT CREATE SEQUENCE TO myuser;

--ALTER USER myuser QUOTA UNLIMITED ON USERS;

--CREATE USER eul IDENTIFIED BY "eulPassWord";

--GRANT CREATE SESSION TO eul;
--GRANT CREATE VIEW TO eul;

--CREATE ROLE DB#EUL#READ#R;
--CREATE ROLE DB#EUL#WRITE#W;
